// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, open the file "firebase.json" in the root of the project.
// The file should have a "project" field with the project ID.
//
// For example:
// {
//   "project": "my-cool-project"
// }
//
// You can also right-click the "firebase.json" file in the file explorer and select
// "Change Firebase Project" from the context menu.

export const firebaseConfig = null;
