// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, open the file "firebase.json" in the root of the project.
// The file should have a "project" field with the project ID.
//
// For example:
// {
//   "project": "my-cool-project"
// }
//
// You can also right-click the "firebase.json" file in the file explorer and select
// "Change Firebase Project" from the context menu.

export const firebaseConfig = {
  "projectId": "studio-5133780745-130d2",
  "appId": "1:1050052849106:web:00fa72fe47d6d4abfa6c0b",
  "apiKey": "AIzaSyDcxZlsp42k0JMHu3tfUMpfluiE9FsYmEs",
  "authDomain": "studio-5133780745-130d2.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "1050052849106"
};
